// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxkmgliuuqlaobbkgcsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4a21nbGl1dXFsYW9iYmtnY3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDQzNjksImV4cCI6MjA2MDIyMDM2OX0.VlgZoVsASyUDmwvr7Wiqj2LZ2KiuI54eePBhlFLhJ1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);